sudo: false
language: python
python:
- 3.6
before_install:
- openssl aes-256-cbc -K $encrypted_bfa6623c8d1e_key -iv $encrypted_bfa6623c8d1e_iv
  -in secrets.tar.enc -out secrets.tar -d
- tar xvf secrets.tar
- mkdir -p lib
install:
- pip install -r requirements.txt
script:
- echo "Running the Test"
- python unit_tests_travis.py
deploy:
  provider: gae
  skip_cleanup: true
  keyfile: client-secret.json
  project: wemove-184522
  default: true
  on: master
