"""empty message

Revision ID: 099524832ec2
Revises: f668f0d0d8ae
Create Date: 2017-12-07 02:11:04.682198

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '099524832ec2'
down_revision = 'f668f0d0d8ae'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('drivers', sa.Column('height', sa.Integer(), nullable=True))
    op.add_column('drivers', sa.Column('picture', sa.Unicode(length=10000), nullable=True))
    op.add_column('drivers', sa.Column('width', sa.Integer(), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('drivers', 'width')
    op.drop_column('drivers', 'picture')
    op.drop_column('drivers', 'height')
    # ### end Alembic commands ###
