"""empty message

Revision ID: 1f6cbae8c4b6
Revises: 61ed9777cb9f
Create Date: 2017-12-06 11:28:51.405300

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision = '1f6cbae8c4b6'
down_revision = '61ed9777cb9f'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('drivers', sa.Column('location', sa.Unicode(length=255), nullable=True))
    op.add_column('drivers', sa.Column('price_base', sa.Integer(), nullable=True))
    op.add_column('drivers', sa.Column('price_per_mile', sa.Integer(), nullable=True))
    op.add_column('drivers', sa.Column('rating', sa.Integer(), nullable=True))
    op.add_column('drivers', sa.Column('tier', sa.Unicode(length=255), nullable=True))
    op.drop_column('drivers', 'locationLng')
    op.drop_column('drivers', 'phoneNumber')
    op.drop_column('drivers', 'locationLat')
    op.add_column('requests', sa.Column('destination', sa.Unicode(length=255), nullable=True))
    op.add_column('requests', sa.Column('source', sa.Unicode(length=255), nullable=True))
    op.drop_column('requests', 'sourceLng')
    op.drop_column('requests', 'sourceLat')
    op.drop_column('requests', 'destinationLat')
    op.drop_column('requests', 'destinationLng')
    op.add_column('users', sa.Column('location', sa.Unicode(length=255), nullable=True))
    op.drop_column('users', 'phoneNumber')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('users', sa.Column('phoneNumber', sa.INTEGER(), autoincrement=False, nullable=True))
    op.drop_column('users', 'location')
    op.add_column('requests', sa.Column('destinationLng', postgresql.DOUBLE_PRECISION(precision=53), autoincrement=False, nullable=True))
    op.add_column('requests', sa.Column('destinationLat', postgresql.DOUBLE_PRECISION(precision=53), autoincrement=False, nullable=True))
    op.add_column('requests', sa.Column('sourceLat', postgresql.DOUBLE_PRECISION(precision=53), autoincrement=False, nullable=True))
    op.add_column('requests', sa.Column('sourceLng', postgresql.DOUBLE_PRECISION(precision=53), autoincrement=False, nullable=True))
    op.drop_column('requests', 'source')
    op.drop_column('requests', 'destination')
    op.add_column('drivers', sa.Column('locationLat', postgresql.DOUBLE_PRECISION(precision=53), autoincrement=False, nullable=True))
    op.add_column('drivers', sa.Column('phoneNumber', sa.INTEGER(), autoincrement=False, nullable=True))
    op.add_column('drivers', sa.Column('locationLng', postgresql.DOUBLE_PRECISION(precision=53), autoincrement=False, nullable=True))
    op.drop_column('drivers', 'tier')
    op.drop_column('drivers', 'rating')
    op.drop_column('drivers', 'price_per_mile')
    op.drop_column('drivers', 'price_base')
    op.drop_column('drivers', 'location')
    # ### end Alembic commands ###
