"""empty message

Revision ID: 1feb28ca4b65
Revises: e4ad25f447e7
Create Date: 2017-12-07 00:02:22.176768

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '1feb28ca4b65'
down_revision = 'e4ad25f447e7'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('drivers', sa.Column('picture', sa.LargeBinary(), nullable=True))
    op.add_column('users', sa.Column('picture', sa.LargeBinary(), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('users', 'picture')
    op.drop_column('drivers', 'picture')
    # ### end Alembic commands ###
