"""empty message

Revision ID: 917541c30471
Revises: 772cafbb1cc8
Create Date: 2017-11-14 02:11:42.729133

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '917541c30471'
down_revision = '772cafbb1cc8'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('stations1',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('lat', sa.Float(), nullable=True),
    sa.Column('lng', sa.Float(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('stations1')
    # ### end Alembic commands ###
