"""empty message

Revision ID: e4ad25f447e7
Revises: 1f6cbae8c4b6
Create Date: 2017-12-06 23:13:35.095028

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'e4ad25f447e7'
down_revision = '1f6cbae8c4b6'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('requests', sa.Column('rating', sa.Unicode(length=255), nullable=True))
    op.drop_column('requests', 'source')
    op.drop_column('requests', 'price')
    op.drop_column('requests', 'destination')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('requests', sa.Column('destination', sa.VARCHAR(length=255), autoincrement=False, nullable=True))
    op.add_column('requests', sa.Column('price', sa.INTEGER(), autoincrement=False, nullable=True))
    op.add_column('requests', sa.Column('source', sa.VARCHAR(length=255), autoincrement=False, nullable=True))
    op.drop_column('requests', 'rating')
    # ### end Alembic commands ###
