"""empty message

Revision ID: f668f0d0d8ae
Revises: 1feb28ca4b65
Create Date: 2017-12-07 00:34:29.226621

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision = 'f668f0d0d8ae'
down_revision = '1feb28ca4b65'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('drivers', 'picture')
    op.add_column('users', sa.Column('height', sa.Integer(), nullable=True))
    op.add_column('users', sa.Column('width', sa.Integer(), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('users', 'width')
    op.drop_column('users', 'height')
    op.add_column('drivers', sa.Column('picture', postgresql.BYTEA(), autoincrement=False, nullable=True))
    # ### end Alembic commands ###
